// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface Seo {
  index?: boolean;
  follow?: boolean;
  title?: string;
  description?: string;
  image?: { data: Media };
}
export interface Seo_Plain {
  index?: boolean;
  follow?: boolean;
  title?: string;
  description?: string;
  image?: Media_Plain;
}

export interface Seo_NoRelations {
  index?: boolean;
  follow?: boolean;
  title?: string;
  description?: string;
  image?: number;
}

