services:
  palm-beach-cannes-strapi:
    container_name: palm-beach-cannes-strapi
    image: ghcr.io/sombrero-studio/palm-beach-backend:${IMAGE_TAG}
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - palm-beach-cannes-network
      - proxy-net
    expose:
      - 1337
    depends_on:
      - palm-beach-cannes-db

  palm-beach-cannes-db:
    container_name: palm-beach-cannes-db
    image: postgres:14.0-alpine
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - palm-beach-cannes-data:/var/lib/postgresql/data/ #using a volume
    networks:
      - palm-beach-cannes-network
      - db-admin-net
    expose:
      - 5432

volumes:
  palm-beach-cannes-data:
    name: palm-beach-cannes-data

networks:
  palm-beach-cannes-network:
    name: palm-beach-cannes-network
  proxy-net:
    external: true
    name: proxy-net
  db-admin-net:
    external: true
    name: db-admin-net
