// Interface automatically generated by schemas-to-ts

import { Seo } from '../components/shared/Seo';
import { Seo_Plain } from '../components/shared/Seo';
import { Seo_NoRelations } from '../components/shared/Seo';

export interface DesignersPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    slug?: string;
    transparentHeader?: boolean;
    spinningIcon?: boolean;
    seo?: Seo;
    blocks?: any;
    locale: string;
    localizations?: { data: DesignersPage[] };
  };
}
export interface DesignersPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  seo?: Seo_Plain;
  blocks?: any;
  locale: string;
  localizations?: DesignersPage_Plain[];
}

export interface DesignersPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  seo?: Seo_NoRelations;
  blocks?: any;
  locale: string;
  localizations?: DesignersPage[];
}

export interface DesignersPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  seo?: Seo_Plain;
  blocks?: any;
  locale: string;
  localizations?: DesignersPage[];
}
