// Interface automatically generated by schemas-to-ts

import { Product } from './product';
import { Image } from '../components/elements/Image';
import { Seo } from '../components/shared/Seo';
import { Product_Plain } from './product';
import { Image_Plain } from '../components/elements/Image';
import { Seo_Plain } from '../components/shared/Seo';
import { Image_NoRelations } from '../components/elements/Image';
import { Seo_NoRelations } from '../components/shared/Seo';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Designer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    transparentHeader?: boolean;
    spinningIcon?: boolean;
    keywords?: string;
    products: { data: Product[] };
    coverImage?: Image;
    seo?: Seo;
    blocks?: any;
    rank?: number;
    locale: string;
    localizations?: { data: Designer[] };
  };
}
export interface Designer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  keywords?: string;
  products: Product_Plain[];
  coverImage?: Image_Plain;
  seo?: Seo_Plain;
  blocks?: any;
  rank?: number;
  locale: string;
  localizations?: Designer_Plain[];
}

export interface Designer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  keywords?: string;
  products: number[];
  coverImage?: Image_NoRelations;
  seo?: Seo_NoRelations;
  blocks?: any;
  rank?: number;
  locale: string;
  localizations?: Designer[];
}

export interface Designer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  keywords?: string;
  products: AdminPanelRelationPropertyModification<Product_Plain>;
  coverImage?: Image_Plain;
  seo?: Seo_Plain;
  blocks?: any;
  rank?: number;
  locale: string;
  localizations?: Designer[];
}
