// Interface automatically generated by schemas-to-ts

import { Seo } from '../components/shared/Seo';
import { Seo_Plain } from '../components/shared/Seo';
import { Seo_NoRelations } from '../components/shared/Seo';

export interface DesignFusionSessionPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    slug?: string;
    transparentHeader?: boolean;
    spinningIcon?: boolean;
    seo?: Seo;
    blocks?: any;
    locale: string;
    localizations?: { data: DesignFusionSessionPage[] };
  };
}
export interface DesignFusionSessionPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  seo?: Seo_Plain;
  blocks?: any;
  locale: string;
  localizations?: DesignFusionSessionPage_Plain[];
}

export interface DesignFusionSessionPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  seo?: Seo_NoRelations;
  blocks?: any;
  locale: string;
  localizations?: DesignFusionSessionPage[];
}

export interface DesignFusionSessionPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  seo?: Seo_Plain;
  blocks?: any;
  locale: string;
  localizations?: DesignFusionSessionPage[];
}
