// Interface automatically generated by schemas-to-ts

import { DownloadFile } from '../components/elements/DownloadFile';
import { DownloadFile_Plain } from '../components/elements/DownloadFile';
import { DownloadFile_NoRelations } from '../components/elements/DownloadFile';

export interface Document {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    internalTitle?: string;
    year?: string;
    downloadFile?: DownloadFile;
    rank?: number;
    locale: string;
    localizations?: { data: Document[] };
  };
}
export interface Document_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  internalTitle?: string;
  year?: string;
  downloadFile?: DownloadFile_Plain;
  rank?: number;
  locale: string;
  localizations?: Document_Plain[];
}

export interface Document_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  internalTitle?: string;
  year?: string;
  downloadFile?: DownloadFile_NoRelations;
  rank?: number;
  locale: string;
  localizations?: Document[];
}

export interface Document_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  internalTitle?: string;
  year?: string;
  downloadFile?: DownloadFile_Plain;
  rank?: number;
  locale: string;
  localizations?: Document[];
}
