// Interface automatically generated by schemas-to-ts

import { Link } from '../components/elements/Link';
import { Image } from '../components/elements/Image';
import { Link_Plain } from '../components/elements/Link';
import { Image_Plain } from '../components/elements/Image';
import { Link_NoRelations } from '../components/elements/Link';
import { Image_NoRelations } from '../components/elements/Image';

export interface Footer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    text?: any;
    policyLinks: Link[];
    socialLinks: Link[];
    newsletterTitle?: string;
    logo?: Image;
    copyright?: any;
    locale: string;
    localizations?: { data: Footer[] };
  };
}
export interface Footer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: any;
  policyLinks: Link_Plain[];
  socialLinks: Link_Plain[];
  newsletterTitle?: string;
  logo?: Image_Plain;
  copyright?: any;
  locale: string;
  localizations?: Footer_Plain[];
}

export interface Footer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: any;
  policyLinks: Link_NoRelations[];
  socialLinks: Link_NoRelations[];
  newsletterTitle?: string;
  logo?: Image_NoRelations;
  copyright?: any;
  locale: string;
  localizations?: Footer[];
}

export interface Footer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: any;
  policyLinks: Link_Plain[];
  socialLinks: Link_Plain[];
  newsletterTitle?: string;
  logo?: Image_Plain;
  copyright?: any;
  locale: string;
  localizations?: Footer[];
}
