// Interface automatically generated by schemas-to-ts

import { LinkImage } from '../components/elements/LinkImage';
import { Link } from '../components/elements/Link';
import { Image } from '../components/elements/Image';
import { LinkImage_Plain } from '../components/elements/LinkImage';
import { Link_Plain } from '../components/elements/Link';
import { Image_Plain } from '../components/elements/Image';
import { LinkImage_NoRelations } from '../components/elements/LinkImage';
import { Link_NoRelations } from '../components/elements/Link';
import { Image_NoRelations } from '../components/elements/Image';

export interface Header {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logo?: LinkImage;
    logoTransparent?: LinkImage;
    headerLinks: Link[];
    hamburgerOpenText?: string;
    hamburgerCloseText?: string;
    hamburgerLinks: Link[];
    socialLinks: Link[];
    searchTitle?: string;
    searchText?: string;
    searchBackToMenuText?: string;
    searchPlaceholderText?: string;
    searchIcon?: Image;
    locale: string;
    localizations?: { data: Header[] };
  };
}
export interface Header_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo?: LinkImage_Plain;
  logoTransparent?: LinkImage_Plain;
  headerLinks: Link_Plain[];
  hamburgerOpenText?: string;
  hamburgerCloseText?: string;
  hamburgerLinks: Link_Plain[];
  socialLinks: Link_Plain[];
  searchTitle?: string;
  searchText?: string;
  searchBackToMenuText?: string;
  searchPlaceholderText?: string;
  searchIcon?: Image_Plain;
  locale: string;
  localizations?: Header_Plain[];
}

export interface Header_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo?: LinkImage_NoRelations;
  logoTransparent?: LinkImage_NoRelations;
  headerLinks: Link_NoRelations[];
  hamburgerOpenText?: string;
  hamburgerCloseText?: string;
  hamburgerLinks: Link_NoRelations[];
  socialLinks: Link_NoRelations[];
  searchTitle?: string;
  searchText?: string;
  searchBackToMenuText?: string;
  searchPlaceholderText?: string;
  searchIcon?: Image_NoRelations;
  locale: string;
  localizations?: Header[];
}

export interface Header_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo?: LinkImage_Plain;
  logoTransparent?: LinkImage_Plain;
  headerLinks: Link_Plain[];
  hamburgerOpenText?: string;
  hamburgerCloseText?: string;
  hamburgerLinks: Link_Plain[];
  socialLinks: Link_Plain[];
  searchTitle?: string;
  searchText?: string;
  searchBackToMenuText?: string;
  searchPlaceholderText?: string;
  searchIcon?: Image_Plain;
  locale: string;
  localizations?: Header[];
}
