// Interface automatically generated by schemas-to-ts

export interface MaterialCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    rank?: number;
    locale: string;
    localizations?: { data: MaterialCategory[] };
  };
}
export interface MaterialCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  rank?: number;
  locale: string;
  localizations?: MaterialCategory_Plain[];
}

export interface MaterialCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  rank?: number;
  locale: string;
  localizations?: MaterialCategory[];
}

export interface MaterialCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  rank?: number;
  locale: string;
  localizations?: MaterialCategory[];
}
