// Interface automatically generated by schemas-to-ts

import { DownloadFile } from '../components/elements/DownloadFile';
import { DownloadFile_Plain } from '../components/elements/DownloadFile';
import { DownloadFile_NoRelations } from '../components/elements/DownloadFile';

export interface MaterialTypology {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    description?: any;
    notes?: any;
    keywords?: string;
    downloadFiles: DownloadFile[];
    rank?: number;
    locale: string;
    localizations?: { data: MaterialTypology[] };
  };
}
export interface MaterialTypology_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: any;
  notes?: any;
  keywords?: string;
  downloadFiles: DownloadFile_Plain[];
  rank?: number;
  locale: string;
  localizations?: MaterialTypology_Plain[];
}

export interface MaterialTypology_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: any;
  notes?: any;
  keywords?: string;
  downloadFiles: DownloadFile_NoRelations[];
  rank?: number;
  locale: string;
  localizations?: MaterialTypology[];
}

export interface MaterialTypology_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: any;
  notes?: any;
  keywords?: string;
  downloadFiles: DownloadFile_Plain[];
  rank?: number;
  locale: string;
  localizations?: MaterialTypology[];
}
