// Interface automatically generated by schemas-to-ts

import { MaterialTypology } from './material-typology';
import { Image } from '../components/elements/Image';
import { MaterialTypology_Plain } from './material-typology';
import { Image_Plain } from '../components/elements/Image';
import { Image_NoRelations } from '../components/elements/Image';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Material {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    typology?: { data: MaterialTypology };
    coverImage?: Image;
    rank?: number;
    locale: string;
    localizations?: { data: Material[] };
  };
}
export interface Material_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  typology?: MaterialTypology_Plain;
  coverImage?: Image_Plain;
  rank?: number;
  locale: string;
  localizations?: Material_Plain[];
}

export interface Material_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  typology?: number;
  coverImage?: Image_NoRelations;
  rank?: number;
  locale: string;
  localizations?: Material[];
}

export interface Material_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  typology?: AdminPanelRelationPropertyModification<MaterialTypology_Plain>;
  coverImage?: Image_Plain;
  rank?: number;
  locale: string;
  localizations?: Material[];
}
