// Interface automatically generated by schemas-to-ts

import { ProductCategory } from './product-category';
import { ProductTypology } from './product-typology';
import { Image } from '../components/elements/Image';
import { Seo } from '../components/shared/Seo';
import { DownloadFile } from '../components/elements/DownloadFile';
import { ProductCategory_Plain } from './product-category';
import { ProductTypology_Plain } from './product-typology';
import { Image_Plain } from '../components/elements/Image';
import { Seo_Plain } from '../components/shared/Seo';
import { DownloadFile_Plain } from '../components/elements/DownloadFile';
import { Image_NoRelations } from '../components/elements/Image';
import { Seo_NoRelations } from '../components/shared/Seo';
import { DownloadFile_NoRelations } from '../components/elements/DownloadFile';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    transparentHeader?: boolean;
    spinningIcon?: boolean;
    category?: { data: ProductCategory };
    typology?: { data: ProductTypology };
    designFusionSessionProduct?: boolean;
    coverImage?: Image;
    keywords?: string;
    seo?: Seo;
    downloadFiles: DownloadFile[];
    blocks?: any;
    rank?: number;
    locale: string;
    localizations?: { data: Product[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  category?: ProductCategory_Plain;
  typology?: ProductTypology_Plain;
  designFusionSessionProduct?: boolean;
  coverImage?: Image_Plain;
  keywords?: string;
  seo?: Seo_Plain;
  downloadFiles: DownloadFile_Plain[];
  blocks?: any;
  rank?: number;
  locale: string;
  localizations?: Product_Plain[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  category?: number;
  typology?: number;
  designFusionSessionProduct?: boolean;
  coverImage?: Image_NoRelations;
  keywords?: string;
  seo?: Seo_NoRelations;
  downloadFiles: DownloadFile_NoRelations[];
  blocks?: any;
  rank?: number;
  locale: string;
  localizations?: Product[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  transparentHeader?: boolean;
  spinningIcon?: boolean;
  category?: AdminPanelRelationPropertyModification<ProductCategory_Plain>;
  typology?: AdminPanelRelationPropertyModification<ProductTypology_Plain>;
  designFusionSessionProduct?: boolean;
  coverImage?: Image_Plain;
  keywords?: string;
  seo?: Seo_Plain;
  downloadFiles: DownloadFile_Plain[];
  blocks?: any;
  rank?: number;
  locale: string;
  localizations?: Product[];
}
