// Interface automatically generated by schemas-to-ts

export interface ProjectCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    rank?: number;
    locale: string;
    localizations?: { data: ProjectCategory[] };
  };
}
export interface ProjectCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  rank?: number;
  locale: string;
  localizations?: ProjectCategory_Plain[];
}

export interface ProjectCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  rank?: number;
  locale: string;
  localizations?: ProjectCategory[];
}

export interface ProjectCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  rank?: number;
  locale: string;
  localizations?: ProjectCategory[];
}
