// Interface automatically generated by schemas-to-ts

export interface AnchorItem {
  text?: string;
  anchorId?: string;
}
export interface AnchorItem_Plain {
  text?: string;
  anchorId?: string;
}

export interface AnchorItem_NoRelations {
  text?: string;
  anchorId?: string;
}

