// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Multimedia } from './Multimedia';
import { Link_Plain } from './Link';
import { Multimedia_Plain } from './Multimedia';
import { Link_NoRelations } from './Link';
import { Multimedia_NoRelations } from './Multimedia';

export enum ChipPosition {
  BottomRight = 'BottomRight',
  TopLeft = 'TopLeft',}

export interface Card {
  internalTitle?: string;
  text?: any;
  chipPosition?: ChipPosition;
  chip?: string;
  link?: Link;
  multimedia?: Multimedia;
  multimediaHover?: Multimedia;
}
export interface Card_Plain {
  internalTitle?: string;
  text?: any;
  chipPosition?: ChipPosition;
  chip?: string;
  link?: Link_Plain;
  multimedia?: Multimedia_Plain;
  multimediaHover?: Multimedia_Plain;
}

export interface Card_NoRelations {
  internalTitle?: string;
  text?: any;
  chipPosition?: ChipPosition;
  chip?: string;
  link?: Link_NoRelations;
  multimedia?: Multimedia_NoRelations;
  multimediaHover?: Multimedia_NoRelations;
}

