// Interface automatically generated by schemas-to-ts

export interface Hotspot {
  internalTitle?: string;
  xCoordinates?: number;
  yCoordinates?: number;
  text?: any;
}
export interface Hotspot_Plain {
  internalTitle?: string;
  xCoordinates?: number;
  yCoordinates?: number;
  text?: any;
}

export interface Hotspot_NoRelations {
  internalTitle?: string;
  xCoordinates?: number;
  yCoordinates?: number;
  text?: any;
}

