// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface Image {
  media?: { data: Media };
  alt?: string;
}
export interface Image_Plain {
  media?: Media_Plain;
  alt?: string;
}

export interface Image_NoRelations {
  media?: number;
  alt?: string;
}

