// Interface automatically generated by schemas-to-ts

export interface Link {
  text?: string;
  url?: string;
  newTab?: boolean;
}
export interface Link_Plain {
  text?: string;
  url?: string;
  newTab?: boolean;
}

export interface Link_NoRelations {
  text?: string;
  url?: string;
  newTab?: boolean;
}

