// Interface automatically generated by schemas-to-ts

import { Image } from './Image';
import { Video } from './Video';
import { Image_Plain } from './Image';
import { Video_Plain } from './Video';
import { Image_NoRelations } from './Image';
import { Video_NoRelations } from './Video';

export interface Multimedia {
  internalTitle?: string;
  desktopImage?: Image;
  mobileImage?: Image;
  showVideo?: boolean;
  desktopVideo?: Video;
  mobileVideo?: Video;
}
export interface Multimedia_Plain {
  internalTitle?: string;
  desktopImage?: Image_Plain;
  mobileImage?: Image_Plain;
  showVideo?: boolean;
  desktopVideo?: Video_Plain;
  mobileVideo?: Video_Plain;
}

export interface Multimedia_NoRelations {
  internalTitle?: string;
  desktopImage?: Image_NoRelations;
  mobileImage?: Image_NoRelations;
  showVideo?: boolean;
  desktopVideo?: Video_NoRelations;
  mobileVideo?: Video_NoRelations;
}

