// Interface automatically generated by schemas-to-ts

export interface Tab {
  title?: string;
  text?: any;
}
export interface Tab_Plain {
  title?: string;
  text?: any;
}

export interface Tab_NoRelations {
  title?: string;
  text?: any;
}

