// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Multimedia } from './Multimedia';
import { Link_Plain } from './Link';
import { Multimedia_Plain } from './Multimedia';
import { Link_NoRelations } from './Link';
import { Multimedia_NoRelations } from './Multimedia';

export interface TableRow {
  textLeft?: string;
  textRight?: string;
  link?: Link;
  multimediaHover?: Multimedia;
}
export interface TableRow_Plain {
  textLeft?: string;
  textRight?: string;
  link?: Link_Plain;
  multimediaHover?: Multimedia_Plain;
}

export interface TableRow_NoRelations {
  textLeft?: string;
  textRight?: string;
  link?: Link_NoRelations;
  multimediaHover?: Multimedia_NoRelations;
}

