// Interface automatically generated by schemas-to-ts

import { Multimedia } from './Multimedia';
import { Multimedia_Plain } from './Multimedia';
import { Multimedia_NoRelations } from './Multimedia';

export interface TeamCard {
  internalTitle?: string;
  name?: any;
  textHover?: any;
  multimedia?: Multimedia;
}
export interface TeamCard_Plain {
  internalTitle?: string;
  name?: any;
  textHover?: any;
  multimedia?: Multimedia_Plain;
}

export interface TeamCard_NoRelations {
  internalTitle?: string;
  name?: any;
  textHover?: any;
  multimedia?: Multimedia_NoRelations;
}

