export default [
  // The array is pre-populated with internal, built-in middlewares, prefixed by `strapi::`
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:", "*.strapi.io"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "https://maps.gstatic.com",
            "https://maps.googleapis.com",
            "khmdb0.google.com",
            "khmdb0.googleapis.com",
            "khmdb1.google.com",
            "khmdb1.googleapis.com",
            "khm.google.com",
            "khm.googleapis.com",
            "khm0.google.com",
            "khm0.googleapis.com",
            "khm1.google.com",
            "khm1.googleapis.com",
            "khms0.google.com",
            "khms0.googleapis.com",
            "khms1.google.com",
            "khms1.googleapis.com",
            "khms2.google.com",
            "khms2.googleapis.com",
            "khms3.google.com",
            "khms3.googleapis.com",
            "streetviewpixels-pa.googleapis.com",
            "market-assets.strapi.io",
            "dl.airtable.com",
            "strapi.io",
            "https://higheredlab.com",
            "https://res.cloudinary.com",
            "s3.amazonaws.com",
            "cdn.jsdelivr.net",
            process.env.AWS_DOMAIN,
          ],
          "font-src": ["'self'"],
          "frame-src": [
            "'self'",
            "youtube.com",
            "www.youtube.com",
            "vimeo.com",
            "*.vimeo.com",
            "facebook.com",
            "www.facebook.com",
            process.env.AWS_DOMAIN,
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "https://maps.gstatic.com",
            "https://maps.googleapis.com",
            process.env.AWS_DOMAIN,
          ],
          "script-src": [
            "'self'",
            "unsafe-inline",
            "https://maps.googleapis.com",
          ],
          "style-src": ["'self'", "'unsafe-inline'"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::cors",
  // custom configuration for internal middleware
  {
    name: "strapi::poweredBy",
    config: {
      poweredBy: "Sombrero Studio",
    },
  },
  "strapi::logger",
  "strapi::query",
  {
    name: "strapi::body",
    config: {
      includeUnparsed: true,
      patchKoa: true,
      multipart: true,
    },
  },
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
