// Interface automatically generated by schemas-to-ts

export interface Anchor {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
}
export interface Anchor_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
}

export interface Anchor_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
}

