// Interface automatically generated by schemas-to-ts

import { Link } from '../elements/Link';
import { Link_Plain } from '../elements/Link';
import { Link_NoRelations } from '../elements/Link';

export interface Breadcrumbs {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  links: Link[];
}
export interface Breadcrumbs_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  links: Link_Plain[];
}

export interface Breadcrumbs_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  links: Link_NoRelations[];
}

