// Interface automatically generated by schemas-to-ts

export interface DesignersList {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}
export interface DesignersList_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

export interface DesignersList_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

