// Interface automatically generated by schemas-to-ts

export interface DownloadProducts {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}
export interface DownloadProducts_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

export interface DownloadProducts_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

