// Interface automatically generated by schemas-to-ts

export interface DownloadProductsCopy {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}
export interface DownloadProductsCopy_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

export interface DownloadProductsCopy_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

