// Interface automatically generated by schemas-to-ts

export interface DownloadDocuments {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}
export interface DownloadDocuments_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

export interface DownloadDocuments_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

