// Interface automatically generated by schemas-to-ts

export interface DownloadProductFiles {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}
export interface DownloadProductFiles_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

export interface DownloadProductFiles_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: string;
}

