// Interface automatically generated by schemas-to-ts

export interface Form {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
}
export interface Form_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
}

export interface Form_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
}

