// Interface automatically generated by schemas-to-ts

import { Multimedia } from '../elements/Multimedia';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export interface Hero {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
  multimedia?: Multimedia;
}
export interface Hero_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
  multimedia?: Multimedia_Plain;
}

export interface Hero_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
  multimedia?: Multimedia_NoRelations;
}

