// Interface automatically generated by schemas-to-ts

export interface JournalList {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}
export interface JournalList_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

export interface JournalList_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

