// Interface automatically generated by schemas-to-ts

export interface MarqueeText {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: string;
}
export interface MarqueeText_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: string;
}

export interface MarqueeText_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: string;
}

