// Interface automatically generated by schemas-to-ts

import { Multimedia } from '../elements/Multimedia';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export interface MasonryGallery {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  multimedia: Multimedia[];
}
export interface MasonryGallery_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  multimedia: Multimedia_Plain[];
}

export interface MasonryGallery_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  multimedia: Multimedia_NoRelations[];
}

