// Interface automatically generated by schemas-to-ts

export interface MaterialsList {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}
export interface MaterialsList_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

export interface MaterialsList_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

