// Interface automatically generated by schemas-to-ts

export interface ProjectsListCopy {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}
export interface ProjectsListCopy_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

export interface ProjectsListCopy_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

