// Interface automatically generated by schemas-to-ts

export interface ProjectsList {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}
export interface ProjectsList_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

export interface ProjectsList_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  loadMoreText?: string;
}

