// Interface automatically generated by schemas-to-ts

export interface ProjectInfo {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
}
export interface ProjectInfo_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
}

export interface ProjectInfo_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
}

