// Interface automatically generated by schemas-to-ts

import { Link } from '../elements/Link';
import { Link_Plain } from '../elements/Link';
import { Link_NoRelations } from '../elements/Link';

export interface Quote {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: string;
  subtext?: any;
  link?: Link;
}
export interface Quote_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: string;
  subtext?: any;
  link?: Link_Plain;
}

export interface Quote_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: string;
  subtext?: any;
  link?: Link_NoRelations;
}

