// Interface automatically generated by schemas-to-ts

import { Multimedia } from '../elements/Multimedia';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export interface SingleMedia {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  fullWidth?: boolean;
  multimedia?: Multimedia;
}
export interface SingleMedia_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  fullWidth?: boolean;
  multimedia?: Multimedia_Plain;
}

export interface SingleMedia_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  fullWidth?: boolean;
  multimedia?: Multimedia_NoRelations;
}

