// Interface automatically generated by schemas-to-ts

import { TeamCard } from '../elements/TeamCard';
import { TeamCard_Plain } from '../elements/TeamCard';
import { TeamCard_NoRelations } from '../elements/TeamCard';

export interface SliderTeamCards {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cards: TeamCard[];
}
export interface SliderTeamCards_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cards: TeamCard_Plain[];
}

export interface SliderTeamCards_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cards: TeamCard_NoRelations[];
}

