// Interface automatically generated by schemas-to-ts

export interface Spacer {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  pxDesktop?: number;
  pxMobile?: number;
  backgroundColor?: any;
}
export interface Spacer_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  pxDesktop?: number;
  pxMobile?: number;
  backgroundColor?: any;
}

export interface Spacer_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  pxDesktop?: number;
  pxMobile?: number;
  backgroundColor?: any;
}

