// Interface automatically generated by schemas-to-ts

import { Link } from '../elements/Link';
import { Link_Plain } from '../elements/Link';
import { Link_NoRelations } from '../elements/Link';

export interface Text {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
  link?: Link;
  chip?: Link;
}
export interface Text_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
  link?: Link_Plain;
  chip?: Link_Plain;
}

export interface Text_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  text?: any;
  link?: Link_NoRelations;
  chip?: Link_NoRelations;
}

