// Interface automatically generated by schemas-to-ts

import { Card } from '../elements/Card';
import { Card_Plain } from '../elements/Card';
import { Card_NoRelations } from '../elements/Card';

export interface ThreeColumnsCards {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cards: Card[];
}
export interface ThreeColumnsCards_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cards: Card_Plain[];
}

export interface ThreeColumnsCards_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cards: Card_NoRelations[];
}

