// Interface automatically generated by schemas-to-ts

export enum Alignment {
  Left = 'Left',
  Center = 'Center',
  Right = 'Right',}

export interface Title {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  alignment?: Alignment;
  text?: any;
}
export interface Title_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  alignment?: Alignment;
  text?: any;
}

export interface Title_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  alignment?: Alignment;
  text?: any;
}

