// Interface automatically generated by schemas-to-ts

import { Card } from '../elements/Card';
import { Card_Plain } from '../elements/Card';
import { Card_NoRelations } from '../elements/Card';

export interface TwoColumnsCards {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  cards: Card[];
}
export interface TwoColumnsCards_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  cards: Card_Plain[];
}

export interface TwoColumnsCards_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  cards: Card_NoRelations[];
}

