// Interface automatically generated by schemas-to-ts

import { Multimedia } from '../elements/Multimedia';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export interface TwoMediaMasonry {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  multimediaLeft: Multimedia[];
  multimediaRight: Multimedia[];
}
export interface TwoMediaMasonry_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  multimediaLeft: Multimedia_Plain[];
  multimediaRight: Multimedia_Plain[];
}

export interface TwoMediaMasonry_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  multimediaLeft: Multimedia_NoRelations[];
  multimediaRight: Multimedia_NoRelations[];
}

