// Interface automatically generated by schemas-to-ts

import { Tab } from '../elements/Tab';
import { Tab_Plain } from '../elements/Tab';
import { Tab_NoRelations } from '../elements/Tab';

export interface VerticalTabs {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: any;
  tabs: Tab[];
}
export interface VerticalTabs_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: any;
  tabs: Tab_Plain[];
}

export interface VerticalTabs_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  title?: any;
  tabs: Tab_NoRelations[];
}

